---
title: "AtelierArith の 計算物理春の学校 2024 講義ノート"
---


## 概要

本講義では計算物理春の学校を受講する上で基礎となるプログラミング・ソフトウェア開発の基礎を学ぶ．

講義の前半は研究開発のために行うソフトウェア開発のワークフローを紹介する．

具体的にはソースコードを管理する Git および Git リポジトリをオンラインで管理する
GitHub の使い方について触れる．また GitHub は他者とのコラボレーションを可能とするプラットフォームの役割を果たすことを理解するために
事前に用意したリポジトリに対してプルリクエストを送りコントリビューションをすることを
体験する．受講者は与えられたツールを単に利用する立場から脱却し，我々は個々の能力を外部に発信する機会が与えられており，
作る側・造る側・創る側の立場になれることを実感できるだろう．これらのワークフローは開発初期のクローズドな環境でも利用できる．
受講の際に得られた知識を今後の研究活動の促進に役立ってもらいたい．

講義の後半は前半に触れたワークフローを実践する材料としてプログラミング言語 Julia を用いる．小規模な開発を VS Code，Pluto Notebook上で行いプロトタイプの作成，実装，テストの記述のサイクルを行う効率よく行う方法を紹介する．必要に応じて Python，Jupyter Notebook も含めたハンズオン・ライブコーディングもする．

講義に用いるノート，環境構築に関するノートはなるべく公開する予定である．各自の今後の学習に役に立ってほしいと考えている．
計算物理の研究室ではソフトウェアは単にツール・道具とみなされ体系的な学習リソースに出会える機会が少なく，
個々のアドホックなスキルの習得によって苦痛を味わいながら研究を進めざるを得ないのが現実である．
本講義がそういった課題の解決にいくつか解決・貢献できれば幸いである．

## 講義資料のリンク

- [Part1](part1/lecture.qmd)
  - [OkinawaCompPhysFoodSurvey2024.jl](https://atelierarith.github.io/OkinawaCompPhysFoodSurvey2024.jl/dev/)
- [Part2](part2/lecture.qmd)
  - [intro2software_with_julia_pluto_materials](https://atelierarith.github.io/intro2software_with_julia_pluto_materials/)
- [Preparation](preparation/lecture.qmd)
